/** Every current app screen, menu and nested disclosure. Source routes are stable IDs, not invented states. */
export const SCREEN_CASES = [
  ...['dashboard','nutrition','training','body','insights','history','inbox','life','settings'].map(view=>({id:view,group:view==='dashboard'||view==='nutrition'?'health':view==='training'?'training':view==='body'||view==='insights'||view==='history'?'body':'life-settings',view,kind:'screen'})),
  ...['upper','lower','rest','missing'].map(id=>({id:'workout-'+id,group:'training',view:'workout/'+id,kind:'screen'})),
];

export const MENU_CASES = [
  {id:'watch-review',group:'life-settings',view:'settings',steps:[['click','[data-act=watch-setup]'],['click','[data-act=watch-file]'],['file','#watch-file',new URL('./watch-fixture.json',import.meta.url).pathname],['submit','.watch-picker']]},
  {id:'watch-review-auth-open',group:'life-settings',view:'settings',steps:[['click','[data-act=watch-setup]'],['click','[data-act=watch-file]'],['file','#watch-file',new URL('./watch-fixture.json',import.meta.url).pathname],['submit','.watch-picker'],['details','#sheet .inline-connect']]},
  {id:'watch-setup',group:'life-settings',view:'settings',steps:[['click','[data-act=watch-setup]']]},
  {id:'watch-supported-readings',group:'life-settings',view:'settings',steps:[['click','[data-act=watch-setup]'],['details','#sheet details']]},
  {id:'watch-file-picker',group:'life-settings',view:'settings',steps:[['click','[data-act=watch-setup]'],['click','[data-act=watch-file]']]},
  {id:'quick-log',group:'health',view:'dashboard',steps:[['click','[data-act=quick]']]},
  {id:'food-detail',group:'health',view:'nutrition',steps:[['click','[data-food]']]},
  {id:'food-detail-source-open',group:'health',view:'nutrition',steps:[['click','[data-food]'],['details','#sheet details']]},
  {id:'food-log',group:'health',view:'nutrition',steps:[['click','[data-act=food-log]']]},
  {id:'food-log-auth-open',group:'health',view:'nutrition',steps:[['click','[data-act=food-log]'],['details','#sheet .inline-connect']]},
  {id:'food-edit',group:'health',view:'nutrition',steps:[['click','[data-food]'],['click','[data-act=food-edit]']]},
  {id:'food-repeat',group:'health',view:'nutrition',steps:[['click','[data-food]'],['click','[data-act=food-repeat]']]},
  {id:'food-delete-confirm',group:'health',view:'nutrition',steps:[['click','[data-food]'],['click','[data-act=food-edit]'],['click','[data-act=food-delete]']]},
  {id:'recent-food-repeat',group:'health',view:'nutrition',steps:[['click','[data-repeat]']]},
  {id:'recipe-portion',group:'health',view:'nutrition',steps:[['click','[data-recipe]']]},
  {id:'recipe-preview',group:'health',view:'nutrition',steps:[['click','[data-recipe]'],['fill','#recipe-grams','250'],['details','#sheet .inline-connect']]},
  {id:'steps-total',group:'health',view:'dashboard',steps:[['click','[data-act=steps]']]},
  {id:'water-total',group:'health',view:'dashboard',steps:[['click','[data-act=water]']]},
  {id:'day-notes',group:'health',view:'dashboard',steps:[['click','[data-act=notes]']]},
  {id:'daily-checkin',group:'health',view:'dashboard',steps:[['click','[data-life=wellbeing]']]},
  {id:'daily-checkin-auth-open',group:'health',view:'dashboard',steps:[['click','[data-life=wellbeing]'],['details','#sheet .inline-connect']]},
  {id:'unsaved-discard-prompt',group:'health',view:'nutrition',steps:[['click','[data-act=food-log]'],['fill','#food-form [name=name]','Synthetic draft that must be kept'],['click','#sheet [data-act=close-sheet]']]},
  {id:'workout-preview',group:'training',view:'training',steps:[['click','[data-preview]']]},
  {id:'workout-preview-technique-open',group:'training',view:'training',steps:[['click','[data-preview]'],['details','#sheet .exercise-list details']]},
  {id:'recorded-session',group:'training',view:'training',steps:[['click','[data-record]']]},
  {id:'workout-log-custom',group:'training',view:'training',steps:[['click','[data-act=workout-log]']]},
  {id:'workout-log-planned',group:'training',view:'workout/upper',steps:[['click','.detail-footer [data-act=workout-log]']]},
  {id:'workout-log-rest',group:'training',view:'workout/rest',steps:[['click','.detail-footer [data-act=workout-log]']]},
  {id:'workout-log-exercises-open',group:'training',view:'training',steps:[['click','[data-act=workout-log]'],['details','#sheet details'],['click','[data-act=add-exercise]'],['click','[data-act=add-exercise]']]},
  {id:'workout-edit',group:'training',view:'training',steps:[['click','[data-record]'],['click','[data-act=workout-edit]']]},
  {id:'workout-delete-confirm',group:'training',view:'training',steps:[['click','[data-record]'],['click','[data-act=workout-edit]'],['click','[data-act=workout-delete]']]},
  {id:'rest-timer-idle',group:'training',view:'training',steps:[['click','[data-act=timer]']]},
  {id:'rest-timer-running',group:'training',view:'training',steps:[['click','[data-act=timer]'],['click','#sheet [data-seconds="90"]']]},
  {id:'rest-timer-paused',group:'training',view:'training',steps:[['click','[data-act=timer]'],['click','#sheet [data-seconds="90"]'],['click','[data-act=timer-pause]']]},
  {id:'body-checkin',group:'body',view:'body',steps:[['click','[data-act=body-log]']]},
  {id:'body-checkin-measurements-auth-open',group:'body',view:'body',steps:[['click','[data-act=body-log]'],['details','#sheet details']]},
  {id:'body-historical-edit',group:'body',view:'body',steps:[['click','[data-body-date="2026-10-05"]'],['details','#sheet details']]},
  {id:'body-chart-values-open',group:'body',view:'body',steps:[['details','.chart-data']]},
  {id:'body-chart-bodyfat-mixed-methods',group:'body',view:'body',variant:{mixedMethods:true},steps:[['select','#metric-select','bodyFatPct'],['details','.chart-data']]},
  {id:'body-chart-all-range',group:'body',view:'body',steps:[['click','[data-range=all]'],['details','.chart-data']]},
  {id:'insights-values-open',group:'body',view:'insights',steps:[['details','.life-chart details']]},
  {id:'program-notes-open',group:'training',view:'training',steps:[['details','.disclosure']]},
  {id:'workout-technique-open',group:'training',view:'workout/upper',steps:[['details','.exercise-list details']]},
  {id:'add-task',group:'life-settings',view:'life',steps:[['click','[data-life=task-add]']]},
  {id:'add-delivery',group:'life-settings',view:'life',steps:[['click','[data-life=delivery-add]']]},
  {id:'saved-facts',group:'life-settings',view:'life',steps:[['click','[data-life=saved-facts]']]},
  {id:'completed-tasks-open',group:'life-settings',view:'life',steps:[['details','.completed-tasks']]},
  {id:'inbox-unread',group:'life-settings',view:'inbox',steps:[['click','[data-filter=unread]']]},
  {id:'inbox-action',group:'life-settings',view:'inbox',steps:[['click','[data-filter=action]']]},
  {id:'inbox-noise',group:'life-settings',view:'inbox',steps:[['click','[data-filter=noise]']]},
  {id:'cleanup-review-trash',group:'life-settings',view:'inbox',steps:[['fill','#cleanup-form textarea','Codex auto review'],['submit','#cleanup-form']]},
  {id:'cleanup-review-archive',group:'life-settings',view:'inbox',steps:[['fill','#cleanup-form textarea','Codex auto review'],['submit','#cleanup-form'],['select','#cleanup-operation','archive']]},
  {id:'cleanup-review-read',group:'life-settings',view:'inbox',steps:[['fill','#cleanup-form textarea','Codex auto review'],['submit','#cleanup-form'],['select','#cleanup-operation','read']]},
  {id:'gmail-setup',group:'life-settings',view:'settings',steps:[['click','[data-life=gmail-connect]']]},
  {id:'gmail-setup-redirect-copy',group:'life-settings',view:'settings',steps:[['click','[data-life=gmail-connect]'],['click','[data-life=gmail-copy-redirect]']]},
  {id:'github-connect',group:'life-settings',view:'settings',steps:[['click','[data-act=connect]']]},
  {id:'targets-profile',group:'life-settings',view:'settings',steps:[['click','[data-act=targets]']]},
  {id:'targets-profile-auth-open',group:'life-settings',view:'settings',steps:[['click','[data-act=targets]'],['details','#sheet .inline-connect']]},
  {id:'sync-diagnostics',group:'life-settings',view:'settings',steps:[['click','[data-act=sync-info]']]},
  {id:'daily-brief',group:'health',view:'settings',steps:[['click','[data-act=brief]']]},
  {id:'reviewed-app-update',group:'life-settings',view:'settings',variant:{updateReady:true},steps:[['click','[data-act=pwa-update]']]},
];

export const STATE_CASES = [
  {id:'dashboard-historical',group:'states',view:'dashboard',date:'2026-10-05'},
  ...['dashboard','nutrition','training','body','insights','history','inbox','life'].map(view=>({id:view+'-empty',group:'states',view,variant:{empty:true}})),
  ...['dashboard','inbox','life','settings'].map(view=>({id:view+'-private-error',group:'states',view,variant:{privateError:true}})),
  {id:'boot-loading',group:'states',view:'dashboard',variant:{loadDelay:2500},boot:true},
  {id:'boot-no-data-error',group:'states',view:'dashboard',variant:{healthError:true},boot:true,waitAfter:500},
  {id:'offline-first-visit',group:'states',view:'dashboard',variant:{offline:true,healthError:true,privateError:true},boot:true,waitAfter:500},
  ...['dashboard','inbox','life'].map(view=>({id:view+'-offline-saved-health',group:'states',view,afterOffline:true})),
  {id:'training-paused',group:'states',view:'training',variant:{trainingStatus:'paused'}},
  {id:'training-clearance-unconfirmed',group:'states',view:'training',variant:{trainingStatus:'awaiting clearance'}},
  {id:'app-update-recovery-ready',group:'states',recovery:true,variant:{updateReady:true}},
  {id:'app-update-recovery-latest',group:'states',recovery:true},
  {id:'app-update-recovery-offline',group:'states',recovery:true,variant:{offline:true}},
];

export const ADDITIONAL_CHECKS = [
  'Each form expanded inline GitHub disclosure, validation error, GitHub authorization rejection, save busy/error and retained draft; connected/disconnected status.',
  'Every body metric (15), units metric/imperial and 7D/30D/90D/All ranges; mixed body-fat methods; record-value tables horizontally scroll only in their container.',
  'Workout custom/planned/rest, completion empty/completed/partial, exercises add/remove, exercise notes expanded, prescribed timer chip and timer dock reopen/stop.',
  'Cleanup select/deselect all, no supported matches, unsupported query, preview error, apply error, chosen trash/archive/read state and retained selection.',
  'Gmail client JSON missing/invalid/wrong type/mismatched redirect/imported review; connected/import disabled; storage/encryption unavailable; clipboard error.',
  'Notifications unsupported/denied/granted and scanning busy/failure; external browser permission dialogs are not app-owned pixels.',
  'Saved curiosities empty/long collection; long pickup codes/tracking/location, completed/undo statuses, source email links.',
  'PWA reviewed update guard during health/private save and dirty form; recovery page checking/error/latest/waiting; explicit apply with isolated SW mock.',
  'Android keyboard reduced viewport 500px with focused input/textarea and scroll to final save/cancel; 424/390/360 widths; 100/130/200% actual computed text scaling.',
  'Real-motion menu open/close/nested replacement/unsaved prompt at 0/80/160/320/650ms, no flicker/disappearance/floating-dock obstruction; reduced-motion equivalent.',
  'Native select option lists and native date picker are browser-owned UI: validate labels/options/selection then inspect available browser screenshots without inventing app popups.',
  'All document and modal surfaces top/every overlapping viewport/bottom inspected by builder and independent reviewer. DOM candidates cannot substitute for inspection.',
];
export const ALL_CASES = [...SCREEN_CASES,...MENU_CASES,...STATE_CASES];
