import {mkdir,writeFile} from 'node:fs/promises';
import {createFixture,gotoView,captureScroll,settle,expandDetails,scaleText,DATE,EVIDENCE} from './fixture.mjs';
const directory=EVIDENCE+'/training-body',width=Number(process.argv[2]||424),textScale=Number(process.argv[3]||100),height=Number(process.argv[4]||924),mode=process.argv[5]||'full';
await mkdir(directory,{recursive:true});
const f=await createFixture({width,textScale,height,mixedMethods:true}),{page}=f,records=[];
async function closeSheet(page){if(await page.locator('#sheet[open]').count()){await page.locator('#sheet [data-act=close-sheet]').first().click();if(await page.locator('.discard-confirm:not([hidden])').count())await page.locator('[data-act=discard]').click();await page.locator('#sheet[open]').waitFor({state:'hidden'});}}
const prefix=`tb-${width}-${textScale}-${height}`;
async function shot(name){await settle(page);const m=await captureScroll(f,prefix+'-'+name,{directory});records.push({name,files:m.files,samples:m.samples.length,overflows:m.samples.filter(s=>s.diagnostics.horizontalOverflow),clipping:m.samples.flatMap(s=>s.diagnostics.clipCandidates),tiny:m.samples.flatMap(s=>s.diagnostics.tinyTargets),obstructed:m.samples.flatMap(s=>s.diagnostics.obstructed)});}
async function click(s){await page.locator(s).first().click();await settle(page)}
try{
 await gotoView(f,'training');await shot('training');await expandDetails(page,'details.disclosure');await shot('program-notes');
 for(const s of f.health.training.sessions){await gotoView(f,'workout/'+s.id);await shot('prescription-'+s.id);if(s.exercises.length){await expandDetails(page,'.exercise-list details');await shot('technique-'+s.id);}await gotoView(f,'training');await click(`[data-preview="${s.id}"]`);await shot('preview-'+s.id);await closeSheet(page);}
 await gotoView(f,'training');await click('[data-record]');await shot('record-session');await click('[data-act=workout-edit]');await shot('edit-session');await click('[data-act=add-exercise]');await shot('exercise-added');await click('.remove-exercise');await shot('exercise-removed');await click('[data-act=workout-delete]');await shot('delete-session');await closeSheet(page);
 await gotoView(f,'training');await click('[data-act=workout-log]');await shot('log-custom');await page.locator('[name=sessionId]').selectOption('upper');await shot('log-program');await expandDetails(page,'details.measurement-fields');await click('[data-act=add-exercise]');await shot('log-empty-exercise');await page.locator('[name=exerciseName]').fill('A deliberately long custom exercise name with a controlled eccentric movement');await click('[data-act=close-sheet]');await shot('discard-session-changes');await click('[data-act=keep-editing]');await closeSheet(page);
 await gotoView(f,'training');await click('[data-act=timer]');await shot('timer');for(const n of[60,90,120,180]){await click(`[data-seconds="${n}"]`);await shot('timer-preset-'+n)}await click('[data-act=timer-pause]');await shot('timer-paused');await click('[data-act=timer-pause]');await shot('timer-resumed');await click('[data-act=timer-add]');await shot('timer-added30');await closeSheet(page);await shot('timer-dock');await click('[data-act=timer-reset]');await shot('timer-stopped');
 await gotoView(f,'body');await shot('body');
 const keys=['weightKg','bodyFatPct','waist',...(mode==='full'?['neck','shoulders','chest','hips','upperArmLeft','upperArmRight','forearmLeft','forearmRight','thighLeft','thighRight','calfLeft','calfRight']:[])];
 for(const k of keys){await page.locator('#metric-select').selectOption(k);await shot('metric-'+k);await expandDetails(page,'details.chart-data');await shot('values-'+k)}
 await page.locator('#metric-select').selectOption('weightKg');for(const r of[7,30,90,'all']){await click(`[data-range="${r}"]`);await shot('range-'+r)}
 await click('[data-body-date]');await shot('edit-body');await expandDetails(page,'#body-form details.measurement-fields');await shot('body-tape-fields');await closeSheet(page);
 await gotoView(f,'body');await click('[data-act=body-log]');await shot('body-log');await page.locator('[name=weightKg]').fill('82.7');await click('[data-act=close-sheet]');await shot('body-discard');await click('[data-act=keep-editing]');await closeSheet(page);
 await gotoView(f,'body');await click('.body-composition-row[data-life=wellbeing]');await shot('body-muscle-checkin');await closeSheet(page);
 const download=page.waitForEvent('download');await click('[data-act=body-export]');const file=await download;await writeFile(`${directory}/${prefix}-export.csv`,await (await import('node:fs/promises')).readFile(await file.path()));await shot('export-body');
 await gotoView(f,'settings');await click('[data-units=imperial]');await gotoView(f,'body');await shot('body-imperial');await click('[data-act=body-log]');await shot('body-form-imperial');await closeSheet(page);
 await page.setViewportSize({width,height:924});await gotoView(f,'training');await click('[data-act=workout-log]');await page.locator('[name=name]').focus();await page.setViewportSize({width,height:500});await shot('keyboard-log-session');await closeSheet(page);await page.setViewportSize({width,height:924});await gotoView(f,'body');await click('[data-act=body-log]');await page.locator('[name=weightKg]').focus();await page.setViewportSize({width,height:500});await shot('keyboard-body');await closeSheet(page);
 const result={prefix,width,textScale,height,records,errors:f.errors,blocked:f.blocked,writes:f.writes};await writeFile(`${directory}/${prefix}-inventory.json`,JSON.stringify(result,null,2));console.log(JSON.stringify({prefix,menus:records.length,screenshots:records.reduce((n,r)=>n+r.files.length,0),overflows:records.filter(r=>r.overflows.length).map(r=>r.name),clipped:records.filter(r=>r.clipping.length).map(r=>r.name),tiny:records.filter(r=>r.tiny.length).map(r=>r.name),obstructed:records.filter(r=>r.obstructed.length).map(r=>r.name),errors:f.errors,blocked:f.blocked,writes:f.writes}));
}finally{await f.close();}
